# Generated by Django 5.0.6 on 2024-05-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('employee_rig_number', models.TextField()),
            ],
        ),
    ]
